server:
  port: 8022
spring:
  #给项目来个名字
  application:
    name: rabbitmq-consumer
  #配置rabbitMq 服务器
  rabbitmq:
    host: 192.168.1.114
    port: 5672
    username: wzx
    password: wzxv587+.
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual